apiVersion: v1
kind: PersistentVolume
metadata:
  name: gradle-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradle-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
